#!/usr/bin/env python

from setuptools import setup

version = open("files/version.txt").read().strip()
long_description = open("README.md").read().strip()

setup(
    name='Phish4Get',
    version=version,
    description='An amazing phishing tool in python with dual tunneling, 70+ templates and many more!',
    long_description=long_description,
    long_description_content_type='text/markdown',
    author='talhazmedia',
    author_email='mehmetalhaisk@gmail.com',
    license="GPLv3",
    url='https://github.com/talhazmedia/Phish4Get/',
    scripts=['phish4get'],
    install_requires=["requests", "bs4"]
)
